package com.bjpowernode.crm.settings.mapper;

import com.bjpowernode.crm.settings.pojo.User;

import java.util.List;
import java.util.Map;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Mon Jun 13 10:36:40 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Mon Jun 13 10:36:40 CST 2022
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Mon Jun 13 10:36:40 CST 2022
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Mon Jun 13 10:36:40 CST 2022
     */
    User selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Mon Jun 13 10:36:40 CST 2022
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Mon Jun 13 10:36:40 CST 2022
     */
    int updateByPrimaryKey(User record);

    /**
     * @description:根据用户名和密码进行查询
     * @author: dushicheng
     * @date: 2022/6/13 16:59
     * @param: [map]
     * @return: com.bjpowernode.crm.settings.pojo.User
    **/
    User selectByLoginActAndPwd(Map<String,Object> map);
    /**
     * @description:查询所有用户
     * @author: dushicheng
     * @date: 2022/6/16 16:59
     * @param: []
     * @return: java.util.List<com.bjpowernode.crm.settings.pojo.User>
    **/

    List<User> selectAllUsers();
}